logging:
  level: "INFO"
  show_progress: true
  hide_http_requests: true
  file_logging: true
  console_logging: true

model:
  embedding_model_hf: "intfloat/multilingual-e5-small"
  rerank_model: "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1"
  device_rerank: "cpu"
  device: "cpu"

ingestion:
  ignore_columns: None

processing:
  TOC_text: "Table of Contents"
  headers_to_split_on:
    - ["##", "Header 2"]
    - ["###", "Header 3"]
    - ["####", "Header 4"]
  headers_keys: {"Header 1":"# ", "Header 2":"## ", "Header 3":"### ", "Header 4":"#### "}
  OMP_NUM_THREADS: 8
  chunk_size: 400
  chunk_overlap: 75
  batch_size_embeddings: 32
  batch_size_reranking: 8
  split_documents: true

paths:
  cache_dir: "./cache"
  data_dir: "./data"
  log_dir: "./logs"

files:
  document_paths:
    - "D:/Secure-Offline-RAG-System/data/raw/data.txt"
    - "D:/Secure-Offline-RAG-System/data/raw/jobless.pdf"

  train_data: "D:/Secure-Offline-RAG-System/data/raw/train.csv"
  test_data: "D:/Secure-Offline-RAG-System/data/raw/test.csv"
  train_results: "D:/Secure-Offline-RAG-System/data/raw/train_results.csv"
  test_results: "D:/Secure-Offline-RAG-System/data/raw/test_results.csv"

ollama:
  model_name: "qwen2.5:1.5b-instruct"
  base_url: "http://localhost:11434"

vector_store:
  type: "chroma"
  persist_directory: "./cache/chroma_db"
  collection_name: "rag_documents_light"
  top_k: 15
  similarity_threshold: 0.3